# Site settings
title: Kyle Copeland
email: copelandky@gmail.com
description: "I don't know"
baseurl: ""
url: "http://kyle-copeland/github.io"
username: "kyle-copeland"

# Build settings
markdown: kramdown
permalink: pretty
